server:
    port: 8080
    undertow:
        threads:
            worker: 10
            io: 2

spring:
    jpa:
        show-sql: true
        properties:
            "[hibernate.format_sql]": true

mysql:
    url: localhost:3306
    schema: admin_catalog_videos
    username: root
    password: root