server:
    port: 8080
    servlet:
        context-path: /api
    compression:
        enabled: true
        mime-types:
            - text/html
            - text/xml
            - text/plain
            - text/css
            - text/javascript
            - application/javascript
            - application/json
        min-response-size: 1024
    undertow:
        threads:
            worker: 64
            io: 4

logging:
    level:
        ROOT: INFO
        org.fullcycle.admin.catalog: DEBUG

spring:
    datasource:
        url: jdbc:mysql://${mysql.url}/${mysql.schema}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
        username: ${mysql.username}
        password: ${mysql.password}
        hikari:
            auto-commit: false
            connection-timeout: 250
            max-lifetime: 600000
            maximum-pool-size: 20
            minimum-idle: 10
            pool-name: master
    jpa:
        open-in-view: false
        show-sql: false
        hibernate:
            ddl-auto: none
        properties:
            "[hibernate.dialect]": org.hibernate.dialect.MySQLDialect
            "[hibernate.generate_statistics]": false
            "[hibernate.connection.provider_disables_autocommit]": true
    threads:
        virtual:
            enabled: true
    rabbitmq:
        dynamic: ${amqp.admin.auto-create}
        host: ${amqp.host}
        port: ${amqp.port}
        username: ${amqp.username}
        password: ${amqp.password}

springdoc:
    api-docs:
        path: /api-docs
        resolve-schema-properties: true
    override-with-generic-response: false
    paths-to-exclude: /**/api-docs,/swagger-resources/**
    swagger-ui:
        path: /

google:
    cloud:
        credentials: ${GOOGLE_CLOUD_CREDENTIALS}
        project-id: ${GOOGLE_CLOUD_PROJECT_ID}
        storage:
            video-catalog:
                bucket: fullcycle_video_catalog
                connect-timeout: 1000
                read-timeout: 2000
                retry-delay: 50
                retry-max-attempts: 3
                retry-max-delay: 50
                retry-multiplier: 1.0

storage:
    video-catalog:
        filename-pattern: type-{type}
        location-pattern: videoId-{videoId}

amqp:
    admin:
        auto-create: false
    queues:
        video-created:
            exchange: video.events
            routing-key: video.created
            queue: video.created.queue
        video-encoded:
            exchange: video.events
            routing-key: video.encoded
            queue: video.encoded.queue