server:
    port: 8080
    compression:
        enabled: true
        mime-types:
            - text/html
            - text/xml
            - text/plain
            - text/css
            - text/javascript
            - application/javascript
            - application/json
        min-response-size: 1024
    undertow:
        threads:
            worker: 64
            io: 4

spring:
    datasource:
        url: jdbc:mariadb://${mariadb.url}/${mariadb.schema}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
        username: ${mariadb.username}
        password: ${mariadb.password}
        hikari:
            auto-commit: false
            connection-timeout: 250
            max-lifetime: 600000
            maximum-pool-size: 20
            minimum-idle: 10
            pool-name: master
    jpa:
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            "[hibernate.dialect]": org.hibernate.dialect.MariaDBDialect
            "[hibernate.generate_statistics]": false
            "[hibernate.connection.provider_disables_autocommit]": true