server:
    port: 8080
    compression:
        enabled: true
        mime-types:
            - text/html
            - text/xml
            - text/plain
            - text/css
            - text/javascript
            - application/javascript
            - application/json
        min-response-size: 1024
    undertow:
        threads:
            worker: 64
            io: 4

spring:
    datasource:
        url: jdbc:mariadb://${mariadb.url}/${mariadb.schema}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
        username: ${mariadb.username}
        password: ${mariadb.password}
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect