version: "3.8"

services:
    mysql:
        image: docker.io/bitnami/mysql:8.0
        container_name: admin-catalog-videos-mysql
        hostname: mysql
        restart: "no"
        environment:
            MYSQL_USER: admin
            MYSQL_DATABASE: admin_catalog_videos
            ALLOW_EMPTY_PASSWORD: yes
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - admin-videos-mysql-data:/bitnami/mysql/data
        networks:
            - admin-videos-network
        healthcheck:
            test: [ "CMD", "/opt/bitnami/scripts/mysql/healthcheck.sh" ]
            interval: 15s
            timeout: 5s
            retries: 6

    rabbitmq:
        image: rabbitmq:3-management
        container_name: admin-catalog-videos-rabbitmq
        hostname: rabbitmq
        restart: "no"
        environment:
            RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
            RABBITMQ_DEFAULT_VHOST: /
        ports:
            - "15672:15672"
            - "5672:5672"
        volumes:
            - admin-videos-rabbitmq-data:/var/lib/rabbitmq
        networks:
            - admin-videos-network

volumes:
    admin-videos-mysql-data:
        driver: local
    admin-videos-rabbitmq-data:
        driver: local

networks:
    admin-videos-network:
        driver: bridge