version: "3.8"

services:
    mysql:
        image: docker.io/bitnami/mysql:8.0
        container_name: admin-catalog-videos-mysql
        hostname: mysql
        restart: "no"
        environment:
            MYSQL_USER: admin
            MYSQL_DATABASE: admin_catalog_videos
            ALLOW_EMPTY_PASSWORD: yes
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - admin-videos-volume:/bitnami/mysql/data
        networks:
            - admin-videos-network
        healthcheck:
            test: [ "CMD", "/opt/bitnami/scripts/mysql/healthcheck.sh" ]
            interval: 15s
            timeout: 5s
            retries: 6

volumes:
    admin-videos-volume:
        driver: local

networks:
    admin-videos-network:
        driver: bridge