version: "3.7"

services:
    mariadb:
        container_name: admin-catalog-videos-mariadb
        image: mariadb:10.5.16
        restart: "no"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=admin_catalog_videos
        security_opt:
            - seccomp:unconfined
        ports:
            - "3306:3306"
        volumes:
            - admin-videos-volume:/var/lib/mysql
        networks:
            - admin-videos-network

volumes:
    admin-videos-volume:
        driver: local

networks:
    admin-videos-network:
        driver: bridge